### ISSUE TITLE
Support Autocrypt Key Transfer message

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#100]
**Is your feature request related to a problem? Please describe.**
We need to support Autocrypt key transfer messages.

**Describe the solution you'd like**
The core already supports Autocrypt transfer messages https://c.delta.chat/classdc__context__t.html#af327aa51e2e18ce3f5948545a637eac9

**Additional context**
This ticket should handle the creation of the transfer message and also the import of an existing transfer message.

**Comment by florianhaar** [comment]
done
