### ISSUE TITLE
Add about screen

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#102]
**Is your feature request related to a problem? Please describe.**
We need an about screen which gives basic information about the app. This is useful for debugging. Additionally a feedback link (to the GitHub repository) should be present.

The general information should at least contain:

- App name (allows us to know if this is a develop or release build)
- App version

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-208)

**Comment by florianhaar** [comment]
done
