### ISSUE TITLE
Ask for permision "storage" before import/export Keys

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#104]
**Describe the bug**
If no permission is granted export/import will fail.

**Comment by Boehrsi** [comment]
Thanks for your feedback and you are absolutely right. Will be fixed today. 
The check was forgotten and the testing of the new feature was mostly done on devices where the permissions were already granted due to other actions.

**Comment by florianhaar** [comment]
fixed

**Comment by Boehrsi** [comment]
@webratte the fix will be integrated in the next release and starting with this release we will also support  Autocrypt Transfer Messages to simplify the key stuff a bit more :).

**Comment by webratte** [comment]
Great to hear 👍

But just another (off topic) question.

Is it useful to report feature request in this very early state of OX Coi.

Or is it better currently only report bugs.

Probably you have already some features in your mind. 😀

**Comment by Boehrsi** [comment]
We have already a roadmap in our heads, but feel free to report features, as well as bugs. We are always open for ideas. I can't promise those ideas make it into one of the next version, but we will definitely talk about every idea. And if possible we also try to implement requested features, if time and the feature itself fits the project.
