### ISSUE TITLE
Feature request: Show introduction when no chats are found

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#115]
WHEN starting the app for the first time, 
OR WHEN all chats have been deleted manually,
THEN an empty list is shown in the "Chats" tab.

Instead please show a friendly introduction text like:
"Welcome to OX Coi! Please start a new chat by tapping +."

**Comment by Boehrsi** [comment]
Fixed and already merged. 
@florianhaar please have a short look if everything is fine. If there is a problem please reopen the ticket.
