### ISSUE TITLE
Feature request: show introduction for new chat

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#116]
WHEN starting a new chat
THEN the chat messages section is empty.

To make OX Coi more approachable, please show an introduction text like this:
"This is a new chat. Send a message to connect!"

Note: the text should be removed when the user sends the first message.

**Comment by Boehrsi** [comment]
Fixed and already merged. 
@florianhaar please have a short look if everything is fine. If there is a problem please reopen the ticket.
