### ISSUE TITLE
Show profile view when selecting a contact

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#118]
Currently, the behavior when selecting a contact is not ideal.

Current behavior: 
- I tap on a contact and the "edit contact" view is opened

Desired behavior:
- I tap on a contact and "contract profile" view is opened
- This is the same view like the profile screen shown when tapping a the title of a 1:1 chat 
- Instead of "Delete chat" add "Edit contact"
- Show an additional "Delete contact" option. When the contact cannot be deleted, because there are existing chats with the contact, please inform the user about it.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-222)

**Comment by Boehrsi** [comment]
Fixed and already merged. 
@florianhaar please have a short look if everything is fine. If there is a problem please reopen the ticket.

**Comment by florianhaar** [comment]
done
