### ISSUE TITLE
Implement new login UI

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#120]
**Is your feature request related to a problem? Please describe.**
Currently the login UI is pretty basic and not optimal. It should get adjusted in regards to the given designs. Doing this will also alter the flow itself:

- Initial entry screen
- Sign in with provider list (via JSON)
- Sign in with chosen provider
- Details screen that is shown when auto-configure failed or if manual configuration was chosen

For now NO registration flow will be added.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-225)

**Comment by florianhaar** [comment]
Done and merged
