### ISSUE TITLE
Provide setting to handle all messages, messages of contacts and chat-only

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#122]
Currently OX Coi is configured in a way that only shows chat messages and replies to chat messages.

Please add a settings option called "Message syncing":
Add this info text:
* Please choose what kind of messages you would like see.

Provide these options:
* Show only chat messages (by default selected)
* Show only messages of my contacts
* Show all messages, including normal email messages

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-223)

**Comment by florianhaar** [comment]
done and merged
