### ISSUE TITLE
Encryption icon is missing for attachment messages

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#126]
**Describe the bug**
The encryption icon is missing for attachment messages. The lock is only shown for text messages.

**To Reproduce**
Occurrence: always
1. Open a chat
2. Send attachment messages

**Expected behavior**
The lock icon is shown for encrypted messages

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-227)

**Comment by florianhaar** [comment]
fixed
