### ISSUE TITLE
Anti-Mobbing

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#129]
To protect users from unwanted communication when being in a mobbing situation, provide a new Anti-Mobbing setting within the Settings section.

In this section, add the following toggle-option: 
**Only show messages of known contacts**: [on, off = default]
When this setting is set to on:
* Show help info text:
  “Messages from unknown contacts do not appear in chats anymore. Instead, you can access such messages here:”
* “Message from unknown contacts”: link to current invites view.

As described above, when the setting is set to *on*, then incoming invites should not be shown anymore within the chats view, also compare https://github.com/open-xchange/ox-coi/issues/58

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-228)

**Comment by florianhaar** [comment]
Implemented and merged
