### ISSUE TITLE
Support Dark Theme / Mode

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#130]
To allow users to personalize their chat experience, respect the dark theme that users may have activated on new Android devices.

Possibly useful links:
* https://medium.com/flutter/android-dark-theme-in-flutter-9c8070b8b127
* https://developer.android.com/preview/features/darktheme

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-229)

**Comment by Boehrsi** [comment]
Will be implemented as soon as the designs for both themes (light + dark) are ready.

**Comment by Boehrsi** [comment]
Designs for theming are planned to be ready in the next weeks. Removing the "Future" label.

**Comment by Boehrsi** [comment]
Adjusted the title to fit both platforms.
