### ISSUE TITLE
Flag messages

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#134]
**Is your feature request related to a problem? Please describe.**
The user should be able to flag messages in the chat view.

- Add the flag / unflag action to the message action menu in the chat view
- Add an indicator (star) to the messages to show that a message is flagged (the design team should decide where to put the indicator)
- Add a star icon button in the action bar in the chat view (keep the search icon on the right)
- Add the flagged view, which should be opened when pushing the star button in the action bar
  - It should look like the chat view (reuse the chat widget)
  - The title should be "Flagged"
  - The subtitle should be "Your favorite messages"
  - Tapping on the title should do nothing
  - Every message should be displayed with the contact who created the message (like in group chats)
  - Tapping on a message should bring up the message action menu with all normal action, but also with a "Start chat" option
  - Tapping the "Start chat" option should open a chat with the contact who created the initial message

**Additional context**
Required core methods should be added to the plugin.

- dc_msg_is_starred() https://c.delta.chat/classdc__msg__t.html#aa1fa85cab4cdcf7a1cb5565939367ea0
- dc_star_msgs() https://c.delta.chat/classdc__context__t.html#a211ab66e424092c2b617af637d1e1d35
- dc_get_chat_msgs() https://c.delta.chat/classdc__context__t.html#a51353ff6b85fa9278d2ec476c3c95eda
- DC_CHAT_ID_STARRED

**Excluded**

- Filtering by user and similar stuff will be added later

[Internal bug tracker](url)

**Comment by florianhaar** [comment]
implemented and merged
