### ISSUE TITLE
Add visusal feedback if key import was successfullx

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#136]
**Describe the bug**
If I imported a existing key there is no confirmation if it was successfully.

**To Reproduce**
Occurrence: [always / 5 out of 10 times / rarely]
1. Go to profile > settings > security
2. Import a existing kex
3. I don't know if it was successfully

**Expected behavior**
I think there should be a pop up window (or similar) with a text like:
Successfully imported key for user@provider.com fingerprint xyz

**App information (please complete the following information):**
 - App version: 0.8.0 (probably all)

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0

**Comment by Boehrsi** [comment]
Thanks for the input. Normally there should be a toast with a message. We will have a look why it does not appear.

**Comment by Boehrsi** [comment]
Will be fixed by https://github.com/open-xchange/ox-coi/pull/139 and will probably be included in the next release (planned for 01.07.19)

**Comment by florianhaar** [comment]
fixed and merged
