### ISSUE TITLE
Disable text suggestions in server setup fields 

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#138]
**Describe the bug**
When signing into an existing account, currently most input fields seem to have a generic input type. This results in the following undesired behavior of text views:
- After adding a dot in the SMTP or IMAP server field, a space is added
- Sometimes entered text is exchange, e.g. "smtp" is tranferred to "SMTP"
- Upper and lowercase is sometimes guessed

**To Reproduce**
Occurrence: always
1. Start the app for the first time
2. In the login process choose advanced
3. Enter text in the IMAP or SMTP server fields
4. See error, this may depend on the chosen keyboard implementation

**Expected behavior**
Text suggestions should be turned off.
On (native) Android this can be done by setting an Input Type:
edittext.setInputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);
or even
edittext.setInputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS | InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);
markup: android:inputType="textNoSuggestions|textVisiblePassword"

**App information (please complete the following information):**
 - App version: 0.8.0

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 9
 - Keyboard: SwiftKey

**Comment by Boehrsi** [comment]
Fixed
