### ISSUE TITLE
Allow to modify groups

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#143]
After setting up a group, I want to be able to edit the group.

Expected usecases include:
- change the group name
- add a participant
- remove a participant
- change the group profile image (later)

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-249)

**Comment by florianhaar** [comment]
Needed functions:
- Set name:
  - https://c.delta.chat/classdc__context__t.html#a9b55b79050c263a7b13a42b35eb6f41c
- Set image:
  - https://c.delta.chat/classdc__context__t.html#a9173428fc8f5727a04db2172a9aaa044
- Remove contact:
  - https://c.delta.chat/classdc__context__t.html#a72d4db8f0fcb595f11045882284f408f
- Add contact:
  - https://c.delta.chat/classdc__context__t.html#a9360baf78e9b45e45af1de5856b63282

**Comment by Boehrsi** [comment]
Done
