### ISSUE TITLE
Do not scroll the "sign in" button in advanced setup

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#148]
**Describe the bug**
In the advanced view the "sign in" at the top right is scrolled with the view.

**To Reproduce**
Occurrence: [always]
When starting OX Coi for the first time, i.e. you are not signed in:
1. Select Sign In
2. Select Other
3. Select Advanced
4. Scroll advanced view and notice that the select button is moved with the view, ie disappears from the visible area. 

**Expected behavior**
The "sign in" button should always be visible.

**App information (please complete the following information):**
 - App version: 0.9.0

**Smartphone (please complete the following information):**
 - Device: Samsung S8
 - OS: Android

**Comment by florianhaar** [comment]
fixed and merged
