### ISSUE TITLE
No loading indicator while importing contacts

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#156]
**Describe the bug**
While importing contacts from the native address book no progress is shown and the UI is lagging if a huge number of contacts is loaded.

**To Reproduce**
Occurrence: always
1. Go to the contacts screen
2. Click on the import contacts icon in the app bar

**Expected behavior**
A blocking progress is shown while the import is performed.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-272)

**Comment by florianhaar** [comment]
Fixed and merged
