### ISSUE TITLE
SMTP port 25 seems to be hardcoded

### ISSUE THREAD

**Issue by kleini** [open-xchange/ox-coi#162]
Although I configure a different port for SMTP, the app always tries to connect to port 25 for the SMTP connection.

**Comment by Boehrsi** [comment]
That's strange, thanks for the info. I will have a look.

**Comment by kleini** [comment]
![Screenshot_20190717-160656_OX_Coi](https://user-images.githubusercontent.com/1384369/61382493-2f6d1f80-a8ad-11e9-962d-0cf9443bc3fb.png)
![Screenshot_20190717-160709_OX_Coi](https://user-images.githubusercontent.com/1384369/61382494-2f6d1f80-a8ad-11e9-96e6-9f718a068531.png)

**Comment by Boehrsi** [comment]
I were also able to reproduce the problem. We will try to provide a fix soon.

**Comment by Boehrsi** [comment]
@kleini I just tried some stuff and I think this is just a misleading error message (if the app can't connect with the given data, some default cases are tried and only the last failed attempt is shown). I think the login failed for another reason (wrong imap / smtp server?).

**Comment by Boehrsi** [comment]
I just retested the issue with the latest release (https://github.com/open-xchange/ox-coi/releases/tag/0.11.0) and everything worked well, could you @kleini please retest if the problem still exists for you?

**Comment by kleini** [comment]
Issue is solved, I can define now ports on my own.
