### ISSUE TITLE
Fix chat and message list flickering

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#166]
**Describe the bug**
Both lists are flickering sometimes and especially if multiple messages are received. We should add some debouncing or adjust our loading logic.

**To Reproduce**
Occurrence: [sometimes]
1. Go to chat / message list
2. Receive new messages

**Expected behavior**
Smooth updates of the list

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-287)

**Comment by robert-virkus** [comment]
Note that the UI also reloads/flickers when receiving a read notification.

**Comment by Boehrsi** [comment]
Related https://github.com/open-xchange/flutter-deltachat-core/commit/9757d5a9c029c7a64a08dd29af9021f050c589ba
