### ISSUE TITLE
Question: When will you release in App stores?

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#172]
Hi, 
just out of curiosity :
Do you have a idea when you will your first release in App stores (Android an iOS)?

But please don't misunderstand me. 
I don't want you set under pressure. 

I'm really only curios :-D

**Comment by robert-virkus** [comment]
Hi Webratte, we currently plan to release _beta_ versions mid of October, this means using an official beta on Google Play and - if everything works out - a publicly accessible Testflight URL for iOS.

**Comment by webratte** [comment]
Thank you.
I looking forward :+1:

**Comment by Boehrsi** [comment]
Closing this issue, as the question seems to be answered. If further questions arise please just reopen the issue or create a new one.
