### ISSUE TITLE
Missing notification

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#174]
**Describe the bug**
I got no notification if I receive a new message.
I tested it by sending messages via Delta Chat to OX Coi.
For both Apps I use different mail addresses.

**To Reproduce**
Occurrence: always
1. Send a message to your OX Coi address
2. In my mail client I can see this message will moved into the imap deltachat folder.
So OX Coi is active and "see" this message
3. No notification is shown

**Expected behavior**
Notifie me for new messages

**App information (please complete the following information):**
 - App version: 0.11.0
 - Plugin version: I don't know
 - Delta Chat Core version: I don't know
 - Flutter version: I don't know

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0

**Comment by Boehrsi** [comment]
Thanks for the report. For now this makes definitely sense as we haven't implemented background handling. 
We are currently adding push and pull support to get the notifications if the app is in background / killed. Stay tuned for those features, they should appear within the next releases. :)

**Comment by robert-virkus** [comment]
From v0.13.0  (https://github.com/open-xchange/ox-coi/releases) onward we support background updates. Note that there are some bugs around this feature for now and that you need to enable background updates manually.

**Comment by Boehrsi** [comment]
I'm closing this issue for now, as we have a first version of this in place (not as stable and reliable as real push) and we are working on real push support and also a better background refresh (https://github.com/open-xchange/ox-coi/issues/197 and https://github.com/open-xchange/ox-coi/issues/314).
