### ISSUE TITLE
Enter key dosn't work as expected

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#185]
**Describe the bug**
Enter key should insert a new line.

**To Reproduce**
Occurrence: always
1. Open a chat
2. start typing
3. tap "Enter key" to insert a new line
4. keyboard will closed instead a new line will inserted

**Expected behavior**
Enter key should insert a new line.

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.12.0
 - Plugin version: [e.g. 0.4.0]
 - Delta Chat Core version: [e.g. 0.40.0]
 - Flutter version: [e.g. 1.0]

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0 (standard keyboard)

**Additional context**

**Comment by Boehrsi** [comment]
Thanks for the report :+1: . I can confirm this problem. It will probably be fixed within the next release (in ~1 week).

**Comment by Boehrsi** [comment]
The bug fix should be visible after review + merge in the next release.

**Comment by florianhaar** [comment]
implemented and merged
