### ISSUE TITLE
Feature request: Optimize the input field

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#186]
**Is your feature request related to a problem? Please describe.**
Currently it's a "one line input field".
And it's hard to control what is typed already.

**Describe the solution you'd like**
There should a automatic line break at the end of the input field.

And also the input field should grow in the high while typing.
Let's say up to 5 lines.

**Comment by Boehrsi** [comment]
The requested change was implement and should be visible after review + merge in the next release.

**Comment by florianhaar** [comment]
Implemented and merged. The max line count is now 4.
