### ISSUE TITLE
Push Reliability

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#195]
**Describe the bug**
In normal use cases, polling for new messages do not always generated the corresponding push messages.

**To Reproduce**
Occurrence: sometimes
1. Given background updates are enabled
2. Close the app and wait for updates, ask someone to send you updates
3. Sometimes you get updates, sometimes you do not
4. When you start the app, you will get the update intermediately.

One theory: binary messages somehow break updates

**Expected behavior**
Background updates should be reliable.

**App information (please complete the following information):**
 - App version: v0.13.0 (413)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S9]
 - OS: [e.g. Android - we should add this info to the About dialog btw]

**Comment by Boehrsi** [comment]
It seems like the threading is the core problem here. I will have a look as this probably also affects the app while in normal use.

**Comment by Boehrsi** [comment]
Requires https://github.com/open-xchange/flutter-deltachat-core/issues/75 to be finished.
