### ISSUE TITLE
Error by deleting a chat

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#200]
**Describe the bug**
See the errormessage in the screenshot. This message arrived after deleting a chat.

**To Reproduce**
Occurrence: always 
1. Delete a chat
2. See error

**Screenshots**
![Screenshot_20190908-112500](https://user-images.githubusercontent.com/6864851/64486292-94991d80-d22b-11e9-84fa-feaf6159b38c.png)

**App information (please complete the following information):**
 - App version: 0.13.0

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0

**Comment by Boehrsi** [comment]
Confirmed as reproducible. Will be fixed in the next release.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-351)

**Comment by Boehrsi** [comment]
Finally we are ready to release new versions and this issue should be fixed in the latest release. See https://play.google.com/store/apps/details?id=com.openxchange.oxcoi
