### ISSUE TITLE
UI sometimes stuck on QR code scan

### ISSUE THREAD

**Issue by phranck** [open-xchange/ox-coi#228]
**Description**
When scanning a QR code the UI sometimes stuck on _"Waiting for authentication..."_

**Tested on**
 - Simulator: iPhone 8, iPhone XR and iPhone XS
 - Device: iPhone 7
 - OS: iOS 12.4, iOS 13.1

[Internal Bugtracker](https://jira.open-xchange.com/browse/OT-480)

**Comment by Boehrsi** [comment]
We tested this a lot:
Android -> iOS
iOS -> Android
iOS -> iOS

And it worked quite nice on the latest develop.

**Comment by phranck** [comment]
Ok, then... So we can close this issue.
