### ISSUE TITLE
Duplicate view content for "Add Contact" & "Edit Contact"

### ISSUE THREAD

**Issue by phranck** [open-xchange/ox-coi#236]
### Describe the bug
According to the attached screenshots the _"Add Contact"_ and _"Edit Contact"_ forms are two seperate widgets, which is totally redundant. You can spot the difference by the two input fields (they are swapt).

### Screenshots
![AddContact](https://user-images.githubusercontent.com/871198/67585151-4b574b80-f74f-11e9-9c0e-f847b97b138d.png)

![EditContact](https://user-images.githubusercontent.com/871198/67585278-7cd01700-f74f-11e9-87cc-788247d68bd3.png)

**Comment by Boehrsi** [comment]
As a lot of stuff changed in this area I close this issue as "not valid anymore". Please reopen if you think this is still a problem.
