### ISSUE TITLE
Adjust permission strings in the info.plist

### ISSUE THREAD

**Issue by phranck** [open-xchange/ox-coi#241]
**Description**
We have to adjust the permission strings in the `Info.plist` to actually describe what we are using and why. These strings should also be localized!

[Internal Bugtracker](https://jira.open-xchange.com/browse/OT-306)

**Comment by phranck** [comment]
@Boehrsi So, initially I've placed a first set `InfoPlist.strings` files with these Keys/Strings:

```
/* A message that tells the user why the app is requesting access to the device’s camera. */
"NSCameraUsageDescription" = "Access to your Camera is required in order to take photos.";

/* A message that tells the user why the app is requesting access to the user’s contacts. */
"NSContactsUsageDescription" = "Access to your system addressbook is required in order to import contacts to the app addressbook.";

/* A message that tells the user why the app is requesting access to the device’s microphone. */
"NSMicrophoneUsageDescription" = "Access to your Microphone is required in order to take audio messages.";

/* A message that tells the user why the app is requesting access to the user’s photo library. */
"NSPhotoLibraryUsageDescription" = "Access to the Photo Gallery is required in order to add attachments.";

/* A message that tells the user why the app is requesting write-only access to the user’s photo library. */
"NSPhotoLibraryAddUsageDescription" = "Access to the Photo Gallery is required in order to store photos to your photo library";

/* A message that tells the user why the app is requesting access to the user’s calendar data. */
"NSCalendarsUsageDescription" = "Access to your Calenders are required in order to share events with your friends.";

/* A message that tells the user why the app is requesting access to the user’s media library. */
"NSAppleMusicUsageDescription" = "Access to your Media Library is required in order to share music files with your friends.";

/* A message that tells the user why the app is requesting the ability to authenticate with Face ID. */
"NSFaceIDUsageDescription" = "Access to Face ID is required to unlock the app.";

/* A message that tells the user why the app is requesting to send user data to Siri. */
"NSSiriUsageDescription" = "Access to Siri is required.";
```
(please [see here](https://github.com/open-xchange/ox-coi/tree/OT-306_AdjustPermissionStringsInInfoPlist/ios/OX%20Coi))

The languages I used are:  
English, French, German, Italian and Spanish

What I need is:
- [ ] A list of missing languages I should add
- [ ] Refined texts for the base language (English)
- [ ] All needed translations

**Comment by Boehrsi** [comment]
Current languages supported are:
https://github.com/open-xchange/ox-coi/blob/006f086c71dfc2d2ca2245bf73a4b893d6cb73e7/lib/src/l10n/l10n.dart#L61

@robert-virkus please take care of the "message refining part"

As soon as all messages are final in this area I will integrate them into our translation source files, so the next translation round will take care of creating the required strings. We will need a small script to create the translated plist files from our source strings.

**Comment by robert-virkus** [comment]
@phranck is there a reason why some components are uppercase like "Photo Gallery" and others are not like "system addressbook"?  Also, NSSiriUsageDescription does not seem to be complete, ie the reason is missing.

**Comment by phranck** [comment]
@robert-virkus There is no special reason at all. That's why I requested _"Refined texts for the base language (English)"_. Regarding Siri: Since we don't really have support for Siri atm, I actually have no clue about the reason. We need to set the key because of the Flutter permission plugin we are using needs it. So, at the end the reason which is set for this key will never be shown, it just needs to be there.

**Comment by Boehrsi** [comment]
Created a followup ticket for the translation part https://github.com/open-xchange/ox-coi/issues/307
