### ISSUE TITLE
Verified icon not shown

### ISSUE THREAD

**Issue by phranck** [open-xchange/ox-coi#242]
**Describe the bug**
When a contact gets verified by QR code scan, the "Verified Icon" (shield) isn't shown immediately. The app needs to be relaunched instead.

Maybe related: #146 

[Internal Bugtracker](https://jira.open-xchange.com/browse/OT-490)

**Comment by Boehrsi** [comment]
@phranck please verify if this is still the case of if our last updates of the plugin also fixed this problem.

**Comment by phranck** [comment]
@Boehrsi Tested it again. It's still a case.

**Comment by Boehrsi** [comment]
Retested, working as intended.
