### ISSUE TITLE
Preview web links

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#246]
**Describe the solution you'd like**
When pasting an URL or sharing an URL to a chat or when receiving an URL, this web link should be visualized with a title and a preview image.

For YouTube
* use a preview image like `https://img.youtube.com/vi/<insert-youtube-video-id-here>/0.jpg`, compare https://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api and https://stackoverflow.com/questions/3452546/how-do-i-get-the-youtube-video-id-from-a-url
* Additionally place a player symbol on top of the preview

For Vimeo:
* Compare https://stackoverflow.com/questions/1361149/get-img-thumbnails-from-vimeo 

For other pages:
* Extract the following meta information from the HTML code:
  * og:image
  * og:title
 or, when above not present:
  * twitter:title
  * twitter:image

**Additional context**
There should be a corresponding settings entry:
* Title: Preview web links
* Description: Show preview images for sent and received web links.

The whole preview should be tappable, meaning the URL should be opened in the browser when it is clicked.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-493)

**Comment by VP-** [comment]
Don't forget to check that the URL actually leads to the service it's supposed to (Twitter, YT, etc.). And **never** do this for any unconfirmed senders.

**Comment by Boehrsi** [comment]
Depends on https://github.com/open-xchange/ox-coi/issues/247 as this ticket will handle the detection of URLs in general.

**Comment by Boehrsi** [comment]
Requires message content splitting. See [internal bug tracker](https://jira.open-xchange.com/browse/OT-515).
