### ISSUE TITLE
Allow simple markup tags

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#248]
**Is your feature request related to a problem? Please describe.**
It's hard to structure text without formatting.

**Describe the solution you'd like**
It would be great to support the following markup:
```
**bold**
*italic*
_underlined_
* unordered list item 1
* unordered list item 2
1. ordered list item 1
2. ordered list item 2
>  quote
`code`
```

**Describe alternatives you've considered**
We could use HTML

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-495)

**Comment by Boehrsi** [comment]
Requires message content splitting. See [internal bug tracker](https://jira.open-xchange.com/browse/OT-515).
