### ISSUE TITLE
Visualize videos

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#249]
**Is your feature request related to a problem? Please describe.**
Currently videos are visualized with the attachment icon, making it hard to detect them.

**Describe the solution you'd like**
- Videos should be visualized with a preview image and a play button.
- When tapping on the video, playback should start

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-496)

**Comment by Boehrsi** [comment]
We already import the https://pub.dev/packages/video_player, this package should be used to display the video. The play button can be implement via a [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html).
