### ISSUE TITLE
Show photos and videos in app

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#251]
**Is your feature request related to a problem? Please describe.**
Currently photos and videos are shown outside in the app. When I want to see the next photo, I need to go back to the app and then manually select the next photo.

**Describe the solution you'd like**
I want to preview all images (photos, GIFs, PNGs, ...) and videos in an in-app viewer.

This viewer should provide the following features:
- Swipe to the next/previous multimedia element in the current conversation
- support both portrait and landscape mode
- update the preview to use the available space when changing the orientation
- Zoom in/out of images
- Pause, stop, play videos
- Move to a position in a video

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-498)

**Comment by Boehrsi** [comment]
Needs a design (e.g. full screen preview vs. only part of the screen and so on) @robert-virkus

**Comment by Boehrsi** [comment]
**General information for the implementation:** This is the in-app viewer for received / sent data and not the view used for previewing / selecting content which should get shared / send via the app.
