### ISSUE TITLE
Visualize send errors

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#255]
**Is your feature request related to a problem? Please describe.**
* When a message cannot be send at all, no check-mark appears. The user has no interaction option at this point.
* When a message could initially be sent, but then fails to get delivered, ie due to quota problems, this problem is not shown to the user.

**Describe the solution you'd like**
In principle, one of the following situations can arise:
1. Temporary problem, eg network problem. Ideally, messages should be automatically tried to be send again for this type of problems. Ideally, the user has additionally the option to try to send the message again by tapping on the message.
2. Permanent problems like invalid recipient. This problem should be visualized and details of the problem should be shown.
3. Unknown problems that could be either temporary or permanent. Ideally, messages should be automatically retried to be send in this case but after 5 unsuccessful retries, the problem should be assumed to be permanent.

Ideally, retries should be done with increasing delay in between:
1. immediately
2. after 5 sec
3. after 10 sec
4. after 30 sec
5. after 2 min
6. after 5 min
7. after 10 min

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-502)

**Comment by VP-** [comment]
DCC already automatically re-tried failed jobs. It uses exponential back-off, with randomly chosen delays in an exponentially increasing range. I.e. the first retry waits up to a minute, the second retry up to 2 minutes, then up to 4 minutes and so on.

**Comment by Boehrsi** [comment]
We have to map errors sent by the core to actual messages in the chat list here and we also must query information from the core in regards to message states (to get persisted data of the message state, e.g. if the app was restarted).

- Investigate error events + mapping to messages
- Investigate state information for messages
- Which error data we actually get? How can we map this to our error strings?
