### ISSUE TITLE
Improve voice recording UX

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#257]
**Is your feature request related to a problem? Please describe.**
* currently a single tap starts a voice recording, while most other apps have a "hold-to-record" voice option
* it's not possible to listen to the recorded audio before sending it
* it's not possible to pause an audio recording

**Describe the solution you'd like**
Apple iMessage seems to be a nice solution
* Keep pressed to record
* Stop holding for getting the audio
* Additional action for sending

Further topics
* Telegram display the audio-level while it records
* Consider swipe left to cancel for advanced users
* Consider to limit the maximum recording length
* Consider to define multimedia meta data in one coherent way, length, codec, resolution, etc
* Possibly DCC already provides some more information that we can use

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-504)

**Comment by Boehrsi** [comment]
We probably should create a design + flow for this to avoid errors @robert-virkus.
