### ISSUE TITLE
Integrate custom navigation bar

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#258]
**Is your feature request related to a problem? Please describe.**
* on iOS we cannot use the FAB button
* on iOS we should not use a search icon but instead use the integrated search field

**Describe the solution you'd like**
Use https://api.flutter.dev/flutter/cupertino/CupertinoSliverNavigationBar-class.html for all base screens.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-505)

**Comment by Boehrsi** [comment]
**Note:** This will also affect the Android part and will change an important part of the app.

- Remove all not required scroll views (mostly the wrapper one to prevent landscape problems)
- Verify the chat message list is still working

**Comment by Boehrsi** [comment]
**Information:**

- We should use one of the Flutter base widgets for app bars (e.g. https://api.flutter.dev/flutter/material/SliverAppBar-class.html or https://api.flutter.dev/flutter/widgets/PreferredSizeWidget-class.html)
- Create one class for the app bar
- Make the custom app bar configurable (search, leading, trailing actions and a text area which renders different depending of the OS). The configuration should be implicit, so e.g. if a search listener is set, the search is enabled. Please avoid switches if possible
- Please research the best flow how the search component and the required actions can be implement in an optimal way (multiple widgets vs. one widget with multiple children). 
  - A multi widget approach could be helpful for easier integration in the current structure
  - A single widget approach could simplify the overall usage of the widget
- The search part should scroll away in certain situations, so it must be coupled with a scroll controller given by one of the child widgets
- The main app bar must be dismissable, as it should be hidden as soon as the search field is selected (some helpful widgets for this are documented here: https://flutter.dev/docs/development/ui/widgets/animation)

**Comment by Boehrsi** [comment]
This ticket if for both platforms, not only for iOS as the initial issue description states.
