### ISSUE TITLE
Detect and resolve password changed situation

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#260]
**Is your feature request related to a problem? Please describe.**
* When I change the password at my email service provider, this is currently not shown nor resolved in the app.

**Describe the solution you'd like**
* When I changed my password, I expect to be prompted about my new password at the next start.
* After entering the correct updated password, I expect the app to remember this

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-507)
[Internal bug tracker 2](https://jira.open-xchange.com/browse/OT-376)

**Comment by Boehrsi** [comment]
Needs design / concept. @robert-virkus

**Comment by Boehrsi** [comment]
I already prepared the logic, we just need to know what should be done in this situation. Working branch is https://github.com/open-xchange/ox-coi/tree/OT-376

**Comment by Boehrsi** [comment]
We do the following:

- Redirect the user to the login screen. Using the app normally isn't allowed anymore
- No data is deleted
- The mail address is hard coded and can't be altered
- The user must enter the new and valid password to proceed using the app

**Comment by robert-virkus** [comment]
+1

**Comment by Boehrsi** [comment]
@florianhaar please do the following adjustments:

- Please create the new "password changed login required UI"
- Please add a preference to block the app if the password is changed (as soon as login is successfully done the preference should be unset)
- @Boehrsi will take care of setting the preference in case of a password change 
- @Boehrsi will rebase and cleanup https://github.com/open-xchange/ox-coi/tree/OT-376
- @Boehrsi will integrate the required changes to OT-376 to use @florianhaar adjustments

**Comment by Boehrsi** [comment]
Please don't close https://jira.open-xchange.com/browse/OT-376, just move it to **Test requested**.

**Comment by florianhaar** [comment]
Merged to develop
