### ISSUE TITLE
No send/read receipt marks are shown

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#262]
**Describe the bug**
Currently no send/read marks are shown in the chat list, regardless of the state.

**To Reproduce**
Occurrence: [always]
1. Go in a chat and send a messages

**Expected behavior**
One check mark is shown as soon as the message is sent, the second should appear after it's read by the receiver.

**Smartphone (please complete the following information):**
 - OS: iOS

**Additional context**
This could be a type problem when transmitting the state from the core, via the plugin to the app.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-510)

**Comment by phranck** [comment]
@Boehrsi This error is a result of the missing cache handling, which was already done with [this pull request](https://github.com/open-xchange/flutter-deltachat-core/pull/49). So the issue is no more actual.

Can be closed.

**Comment by phranck** [comment]
@CihanOezkan Please have a review and confirm.

**Comment by phranck** [comment]
@Boehrsi I think we have to reopen it. I just discovered that the sent/read marks are shown immediately a message has been sent! Please have a look and confirm or deny it.

**Comment by Boehrsi** [comment]
At least for Android I can't confirm that. @CihanOezkan can you reproduce that? So we could confirm this could be an iOS only bug.

**Comment by phranck** [comment]
After your greater refactoring session, @Boehrsi, I tested the hole thing and now it everything works as expected. Well done! So we can close ticket.
