### ISSUE TITLE
Multiple messages are reloaded on state change

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#270]
**Describe the bug**
If a message in the chat view (so in the messages list) is flagged multiple messages are redrawn (probably all messages above the actual message).

**To Reproduce**
Occurrence: [always]
1. Go to a chat view
2. Long press a message
3. Flag the message

**Expected behavior**
Only the selected message is reloaded.

**Additional context**
This method: https://github.com/open-xchange/ox-coi/blob/2a1f55591371502c2014a82c3a16dc4fdb5024ae/lib/src/chat/chat.dart#L485 
And the given CustomListView should handle this. The list view uses the `Key` of the items to identify and reuse items. The key is build upon the id and the last update timestamp of an item. Normally only the flagged item should change it's key and all other should be stable, so Flutter can reuse the widgets. Somewhere in that area is probably the problem (changed timestamps due to too aggressive update or something like that)

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-516)

**Comment by Boehrsi** [comment]
I'm nearly done with my rewrite of that area, prepare for review. Needs just one more adjustment and a rebase. Everything is based on you initial changes @phranck .

**Comment by phranck** [comment]
I'm curious! 😊

**Comment by Boehrsi** [comment]
Fixed
