### ISSUE TITLE
Swipe to delete in the chat list

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#271]
**Is your feature request related to a problem? Please describe.**
It should be possible to delete chat in the chat list via a swipe to delete action.

**Describe the solution you'd like**

- A swipe from right to left should delete an item
- The visible area behind the item should be red (probably the error color for now) and a trashcan icon should be shown
- Use the Dimissible widget (https://flutter.dev/docs/cookbook/gestures/dismissible) to implement this ticket
- We have to provide an undo action via e.g. a Snackbar https://flutter.dev/docs/cookbook/design/snackbars (therefore we won't delete the chat until the Snackbar disappears, not right after swiping the chat away) 

**Additional context**
For now only handling chats is relevant, handling invites is not part of this ticket and will be done in another ticket.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-426)

**Comment by phranck** [comment]
@Boehrsi You suggest to use the `dismissible` plugin providing this feature. This plugin seems to be very basic. What do you think of using [slidable](https://pub.dev/packages/flutter_slidable) instead. There are way more options which offer us more flexibility.

**Comment by phranck** [comment]
@Boehrsi Additionally: Snackbars are very Android like thing, they are not really used under iOS. Instead a simple alert should be presented (please have a look at [Android VS. iOS: Compare 20 UI Components & Patterns](https://medium.com/@chunchuanlin/android-vs-ios-compare-20-ui-components-patterns-part-1-ad33c2418b45), search for _"Snackbars & Toasts VS. Alerts"_).

**Comment by Boehrsi** [comment]
As discussed the Slidable Plugin looks really good :+1:  and we will not implement the undo part at all (for the moment).
