### ISSUE TITLE
Add pre-defined chat

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#301]
**Is your feature request related to a problem? Please describe.**
- Add a way to inform users about new features
- Allow users to get support

**Describe the solution you'd like**
- Add predefined chat with oxcoimessenger@open-xchange.com, note that the email address as well as the chat name should be configurable
- After an update, create the chat only when it has been deleted before
- Allow to specify one or more update message contents
- After an update or install, add these messages to the chat

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-539)

**Comment by Boehrsi** [comment]
- A new per customer config file
- Add a list of pre-configurable chats to the config file
  - Name
  - Mail
  - Deletable
- Add the chat during initial setup of the app

**Comment by Boehrsi** [comment]
>     * Allow to specify one or more update message contents
>     * After an update or install, add these messages to the chat

This isn't possible without altering the general structure of message handling. We can only setup outgoing messages, not incoming. Adding fake messages is in my opinion a bad idea, as we have to deal with real and fake messages as soon as the user really interacts with the chat. @robert-virkus we have to define how we can circumvent this problem.
