### ISSUE TITLE
Improve Profile Page UI

### ISSUE THREAD

**Issue by cornelhav** [open-xchange/ox-coi#329]
*Situation:*
The current UI is not well designed and misleading.

*To do:*

Integrate the following UI: https://confluence-public.open-xchange.com/display/COIPublic/Profiles+and+Settings

Struktur and Content 
The Profile Page consist of:
Profile Over View 
Settings List 

The Settings List consist of following:

Flagged messages 
Show my QR code
Invite a friend 

Group Header: General Settings
- Notifications
- Chats

Group Header: Email Settings
- Email Signature 
- Server Settings

Group Header: Security
- Privacy and Mobbing protection 
- Blocked Contacts 
- Encryption 

About 
Feedback 

https://jira.open-xchange.com/browse/OT-573

**Comment by Boehrsi** [comment]
Fixed by https://github.com/open-xchange/ox-coi/commit/07877e2acc43ea1a628405d3eabfcc0ce0169e2c
