### ISSUE TITLE
Events not handled correctly

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#334]
**Describe the bug**
Sometimes events aren't handled correctly (e.g. they are missing or send to already unregistered stream handlers). This happens due to an insecure plugin API for the listener handling. 

**Expected behavior**
Reliable event handling and a reliable plugin API.

**Additional context**
The actual logic change is located in the plugin repository.

https://jira.open-xchange.com/browse/OT-578

**Comment by pbleser** [comment]
webhook test 1

**Comment by pbleser** [comment]
webhook test 2

**Comment by pbleser** [comment]
webhook test 3

**Comment by florianhaar** [comment]
Fixed and merged to develop.
