### ISSUE TITLE
Crash if a "could not delivered" error-message is in the inbox

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#344]
- Platform : Android 7
-  OX-Coi Version: beta-3
-  Expected behavior: no crash
-  Actual behavior: crash
-  Steps to reproduce the problem:

1. send a message to a not existing mail address
2. wait until the error message reach the inbox.
3. Crash.
4. not able to start DC until you deleted the error-message.
 After deleting the message I can start OX-Coi normal without a crash.

This is a example of the error message:

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error. The following address(es)
failed:

not-existing-mailaddress@gmx.de:`
SMTP error from remote server for RCPT TO command, host: mx01.emig.gmx.net (212.227.17.5) reason: 550 Requested action not taken: mailbox unavailable



--- The header of the original message is following. ---

```

**Comment by Boehrsi** [comment]
Thanks for your bug report, we will have a look why this is happening. It could be possible that this is already fixed on the development branch and just not released yet (the next release is planned soon, we just have to get rid of one last blocker issue). A fix for this will probably be included in the next release.

**Comment by Boehrsi** [comment]
As a short update: We found the problem and we are currently investigating possible fixes.

**Comment by Boehrsi** [comment]
We probably have a fix now, but sadly it needs some more testing, so it probably won't be in the release, which should be ready starting next week. But we plan a potential bug fix release, which then include this fix. Sorry for the delay, but debugging this wasn't that easy :).

**Comment by Boehrsi** [comment]
The fix will be in the next release. ETA coming soon. Sorry for the long time to fix, but it was a bug pretty deep within the structures.

**Comment by Boehrsi** [comment]
Hi and sorry for the long response cycle. We just released a new version of the app and the problem should now be fixed now. As our tests went well I will close this issue. If you still experience this problem with the latest version (https://github.com/open-xchange/ox-coi/releases/tag/0.600.3) please just reopen it.
