### ISSUE TITLE
iOS: export/import PGP key uses location not accessible to Files app

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#345]
**Describe the bug**
When trying to export or import a key manually, a storage location is used that is not accessible to Apple's Files app. So I cannot access the key.

**To Reproduce**
Occurrence: [always]
1. Go to Settings -> Security -> 
2. Click on Export / Import key
3. Observe shown path

**Expected behavior**
A file path that is accessible to the Files app should be used.

**Screenshots**
![20191220_130044000_iOS](https://user-images.githubusercontent.com/837669/71256524-4a96fc00-2331-11ea-96ad-f101f4641238.png)

**App information (please complete the following information):**
 - App version: [e.g. 0.400.2]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS13.3]

**Additional context**
https://openxchange.userecho.com/helpdesks/3/tickets/121-coiapp-suite-encryption-doesnt-work

**Comment by Boehrsi** [comment]
Normally the given path should be available since we allowed it https://github.com/open-xchange/ox-coi/commit/8be7ad6ae2a72d0daf881e1b5578e167f6b42ea4

We have to verify this one in the latest builds.

**Comment by CihanOezkan** [comment]
This issue is fixed (Ticket can not be linked due to permissions)
