### ISSUE TITLE
E-mail address and ISP login assumed to be the same

### ISSUE THREAD

**Issue by aerique** [open-xchange/ox-coi#346]
**Describe the bug**

To be able to login with OX COI I need to use my ISP's username-as-email address (username `abc`, need to use `abc@example.com` for OX COI), while I actually never use that e-mail address.  I've been using another e-mail address (`xyz@example.com`) on the same ISP for 20+ years which is the one I want to use to be contacted at.  Except it's an alias for historical reasons.

**Expected behavior**

I want the e-mail address I want to be contacted at and the username I use to sign in to my provider to be separated in "Manual steps" when signing in to OX COI.  This is a feature that almost every e-mail application offers.

**App information (please complete the following information):**
 - App version: `beta-3 (2003)`

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Pro
 - OS: EMUI 9.1.0 (Android version 9)

**Comment by omoerbeek** [comment]
Additionally, COI does not seem to be able to handle using different IMAP and SMTP credentials; there's only one username and one password field.

**Comment by robert-virkus** [comment]
Thanks for the reports, all valid complaints that we will address!
