### ISSUE TITLE
Provide login name different from email

### ISSUE THREAD

**Issue by dev4223** [open-xchange/ox-coi#412]
With my email account I have to login into IMAP and SMTP server with a login name different from the email address. So setup of OX Coi is not possible because I can't give a login name. 
Also in OX Coi I want to give an alias email address as account email other than the email accounts email address.

**Comment by Boehrsi** [comment]
Hi, thanks for your report. Are you using the latest version (https://github.com/open-xchange/ox-coi/releases/tag/0.500.1)? As this version supports setting the IMAP / SMTP login names directly and independent from the given mail address (in the manual setup form).
In regards to alias support we already have https://github.com/open-xchange/ox-coi/issues/362 which covers general problems with aliases. But as you are able to set login credentials independent from your mail address in version 0.500.1 it should also be possible to use aliases from within the app.

**Comment by dev4223** [comment]
Hi, ok, checked the version and it was an old one. Don't remember, whether I installed the APK directly and so it didn't update in play store. Now everything worked as expected. Thanks for your work!

**Comment by Boehrsi** [comment]
Thanks for reporting and great that it works now. I'm closing this issue now.
