### ISSUE TITLE
Streamline buttons

### ISSUE THREAD

**Issue by cornelhav** [open-xchange/ox-coi#419]
**Situation**
The button currently differs in many cases like:
- Font transformations
- Semantics of improtancy
- Styling

**To do**
https://confluence-public.open-xchange.com/pages/viewpage.action?pageId=43680583

**Comment by Boehrsi** [comment]
Implementation notes:

- Implement one base button setup
- Implement three variations which are fitting in regards to the designed concepts on top of the base setup
- Use the newly created buttons everywhere (please check the whole project for other button types)
- This ticket only targets the buttons (even though the Confluence page contains icon styles)
