### ISSUE TITLE
imap-coi plugin for dovecot not fully supported?

### ISSUE THREAD

**Issue by Mask66** [open-xchange/ox-coi#422]
**Describe the bug**
OX COI Messenger doesn't recognize incoming messages as chat messages  after enabling the imap-coi plugin on dovecot. So they don't show up in the app. Outgoing messages correctly go to the same folder.

**To Reproduce**
Occurrence: always
1. Install, enable and configure  imap-coi plugin (https://github.com/dovecot/coi) 2.3.9 on dovecot 2.3.9.3
2. Setup an account pointing to that dovecot server.
3. Incoming chat messages no longer show up in the app.

**Expected behavior**
Incoming messages showing up in the chats in the app.

**App information (please complete the following information):**
 - App version: 0.500.1 (2005) (from Google Play Store)
 - Delta Chat Core version: 1.0.0-alpha.5/Android (version information from message headers)

**Smartphone (please complete the following information):**
 - Server:  FreeBSD 12.1-STABLE r358220, dovecot 2.3.9.3, dovecot-coi 2.3.9
 - Device: OnePlus 5T
 - OS: Android 9

**Additional context**

I recently installed the imap-coi plugin (release 2.3.9) on my dovecot 2.3.9.3 installation.

Capabilities reported by the server:

a1 LOGIN [username] [password]
a1 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY WEBPUSH LITERAL+ NOTIFY METADATA SPECIAL-USE COI] 
Logged in

After recreating the account in the android App it correctly enabled the CoI features on the server :

a1 GETMETADATA (DEPTH 1) "" (/private/vendor/vendor.dovecot/coi/config)
* METADATA "" (/private/vendor/vendor.dovecot/coi/config/enabled {3}
yes /private/vendor/vendor.dovecot/coi/config/mailbox-root {3}
COI /private/vendor/vendor.dovecot/coi/config/message-filter {6}
active)
a1 OK Getmetadata completed (0.002 + 0.000 + 0.001 secs).

and created a "COI" folder with a "Chats" subfolder (instead of the previously created "DeltaChat" subfolder).

So far, so good, message filtering works on the dovecot side and chat messages land directly in the relevant subfolder without first being saved to the inbox. 

But the OX COI Messenger doesn't recognize incoming messages as chat messages anymore, so they don't show up in the app. Outgoing messages correctly go to the same folder.

Also I noticed, that after enabling the COI features on my dovecot installation, the 
References: <chat$[...]@[..]> headers stopped being added to outgoing messages and so replies from "normal" email accounts won't show up in the app as well.
 
I will happily provide logs or more information to debug this issue.

**Comment by Boehrsi** [comment]
Thanks for the feedback and sorry for the late response, we will have a look why this happens and if additional logs could be helpful we will respond in this ticket. Thanks for testing the app and also the plugin.

**Comment by Boehrsi** [comment]
Hi and sorry for the long response cycle. We just released a new version of the app and the problem should now be fixed now. As our tests went well I will close this issue. If you still experience this problem with the latest version (https://github.com/open-xchange/ox-coi/releases/tag/0.600.3) please just reopen it.
