### ISSUE TITLE
Re-Import of system contacts doesn't work

### ISSUE THREAD

**Issue by phranck** [open-xchange/ox-coi#426]
### Describe the bug
On iOS I already imported all system contacts running the app in Simulator. After that I deleted some of them and started contacts import again.

### To Reproduce
Occurrence: always
1. Start a fresh installed app
2. Switch to **Contacts**
3. Tap the icon for contacts import
4. Delete some of these imported contacts
5. Tap the icon for contacts import again

### Expected behavior
All deleted contacts should appear after re-import.

### Smartphone (please complete the following information)
 - Device: iPhone Simulator (*iPhone 8*)
 - OS: iOS 12.4

**Comment by Boehrsi** [comment]
Tested this on Android, without problems. So we probably should check the plugin layer here.

**Comment by phranck** [comment]
Strange. I tested it again, and re-import worked now.
**BUT**: Before deleting two of the imported contacts I opened a chat with each, without posting any message. Chats were present then. After deleting these two contacts I had two empty chats in the chat list.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/871198/75690836-d1f2db00-5ca3-11ea-8050-9e4986b1c85a.png">

**Comment by phranck** [comment]
@Boehrsi Can you have a look on Android if you are able to reproduce it, please?

**Comment by Boehrsi** [comment]
Yep, I can confirm this. I will fix this tomorrow.

**Comment by Boehrsi** [comment]
As the re-import is working now and the empty chat bug is fixed, I think we can close this one and monitor if those problems occur again. What do you think @phranck ?
