### ISSUE TITLE
Add tests for flagged messages per chat

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#439]
**Is your feature request related to a problem? Please describe.**
We have now the possibility to show all flagged messages for one chat. The view can be opened via the chat profile view (tap on the name of the chat in the chat view to open). A "Flagged messages" entry should be available.

**Describe the solution you'd like**
Please implement this test similar to the general flagged view tests.

**Comment by Dougnkong** [comment]
Proposed Workflow:

- Login 

- Add two chats

-Edit two messages in the first chat, flags both and return to the chat view.

-Edit one message in the second chat, flags that one, and navigate to the flagged view to check if all flagged messages are available, and back to the chat view.

- Navigate to flagged message though one chat, unflag all message and back to the chat view.
