### ISSUE TITLE
API key exposed

### ISSUE THREAD

**Issue by mrxris1337** [open-xchange/ox-coi#443]
**Describe the bug**

Your api key is showing : )

https://github.com/open-xchange/ox-coi/blob/master/ios/OX%20Coi/Firebase/GoogleService-Info-Development.plist

**To Reproduce**
Occurrence: [always / 5 out of 10 times / rarely]

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App version: [e.g. 0.4.0]
 - Plugin version: [e.g. 0.4.0]
 - Delta Chat Core version: [e.g. 0.40.0]
 - Flutter version: [e.g. 1.0]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Boehrsi** [comment]
Thanks for reporting this. We will clean this up in a future release. It's not a security problem (https://firebase.google.com/docs/projects/learn-more#config-files-objects), but it shouldn't be in the repository nevertheless.
