### ISSUE TITLE
iOS: Some navigation bar titles are hidden in large font mode

### ISSUE THREAD

**Issue by cornelhav** [open-xchange/ox-coi#446]
**Describe the bug**
After setting a bigger font size from the accessibility tool, the information in the navigation bar is hidden. The chat screen is the most affected screen. 

**To Reproduce**
Occurrence: [always]
1. Set a larger font in the native accessibility tool.
2. Enter the app.
3. All fonts should now be bigger.
4. Some textual information are hidden the navigation bar.

**Expected behavior**
The font size in the Navigation Bar is not scaled like the native iOS behavior.

**Comment by Boehrsi** [comment]
Will be fixed in https://github.com/open-xchange/ox-coi/issues/258
