### ISSUE TITLE
Notifications show wrong timestamp and are repeated until message is read

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#447]
**Describe the bug**
For notification messages a wrong timestamp is shown. Additionally, notifications are repeated for unread messages.

**To Reproduce**
Occurrence: [always]
1. Receive a message and do not read it.
2. Wait for the push notification.
3. Start the app without going into the conversation with the unread message.
4. Wait for the next background polling / for the next notifications.
5. A) Observe the timestamp for the message in the notification on the lockscreen.
5. B) Observe that the notification is repeated for the unread message.

**Expected behavior**
* The timestamp for a message should not be the polling time, but the received time.
* When a notifcation for a message has been already shown, it should not be repeated.

**Screenshots**
![PushNotificationForOldUnreadMessage](https://user-images.githubusercontent.com/837669/76526430-cb1b5380-646d-11ea-8f39-ef4db05b1e21.jpg)

**App information (please complete the following information):**
 - App version: [e.g. Beta-5]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS13.3]

**Additional context**

**Comment by robert-virkus** [comment]
Note that in the message in the screenshot is from Friday, March 6th. In the screenshot it seems the message is from Wednesday, March 11th.

**Comment by Boehrsi** [comment]
Fixed by https://github.com/open-xchange/ox-coi/pull/546 

**Note:** We are not altering the timestamp of the notification, as we can't right now. But removing duplicated messages should already help a lot. We will track if setting the timestamp for the notification will be possible in the future.
