### ISSUE TITLE
Sending messages from external mail account to COI-Account doesn't work 

### ISSUE THREAD

**Issue by matthesdr** [open-xchange/ox-coi#462]
**Describe the bug**
Sending messages from external mail account to COI-Account doesn't work. I used OX Appsuite and a Google Mail Account for sending a message to the COI Test user. None of my sent messages were receipt by COI-Messenger.

**To Reproduce**
Occurrence: always
1. Go to "Profile"
2. Click on 'Chat'
3. Click on 'Message syncing'
4. Choose option "Show both chat an email messages from all senders
5. Login to an external email account
6. Try to send a message to the same email address used bei COI-User

**Expected behavior**
The message sent from external email account should appear in COI-Messenger

**App information (please complete the following information):**
 - App version: 0.600.0 (513)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Comment by Boehrsi** [comment]
This seems to be a regression as this worked already in prior versions.

**Comment by phil294** [comment]
[comment removed, as not valid anymore]
