### ISSUE TITLE
Sending files don't work for *.plist and *.rar

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#480]
**Describe the bug**
Sending files don't work. I tested it with a file "config.plist", which disappears directly by clicking "send", and a RAR-File. The RAR-File appears in chat history of sender but wasn't send. The hourglass icon is always visible.

**To Reproduce**
Occurrence: always
1. Go to chat
2. Open a chat
3. Click on "+"-icon
4. Select file
5. Select file e.g. config.plist
6. Send file

**Expected behavior**
The selected file should be sent

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.600.0 (513)
 - Plugin version: 
 - Delta Chat Core version: 
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Additional context**

**Comment by phranck** [comment]
Reopened because of QA tests failed.
