### ISSUE TITLE
Group chat: Leaving the group chat will not be announced in the group

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#487]
**Describe the bug**
Leaving the group chat will not be announced in the group. A user can leave a group chat on his own client. The group chat will be deleted on the client. If I check the member list on an other client, the user is still in the list and no message appears to inform about leaving the group chat.

**To Reproduce**
Occurrence: always
1. Open a new group chat on Client A
2. Invite some contacts from your contacts to the group chat
3. Send a message to the group
4. Open the group chat on client B
5. Tab on group name to open the settings
6. Tab on the button "Leave the group"
7. Confirm the exit

**Expected behavior**
User leaves the group. The chat history disappears. A message is sent to the remaining users that he has left the group. The user is deleted from participant list

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.600.0 (513)
 - Plugin version: 
 - Delta Chat Core version: 
 - Flutter version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4

**Additional context**

**Comment by Boehrsi** [comment]
Fixed in the latest release: https://github.com/open-xchange/ox-coi/releases/tag/0.600.3.
