### ISSUE TITLE
Reply to a group chat message via email should appear in the group chat

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#489]
**Describe the bug**
Reply to a group chat message via email should appear in the group chat. The group chat member doesn't use COI at this moment but is invited to a group chat. If he replies to a group chat message via email, the message appears in a new single chat and not in the group chat.

**To Reproduce**
Occurrence: always
1. Go to Chat
2. Create a group chat
3. Invite some people from your contacts. One of them doesn't use COI
4. Send a message in the group
5. Check email account for incoming chat message
6. Reply to chat message

**Expected behavior**
The message sent via email should appear in the group chat.

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.600.0
 - Plugin version: 
 - Delta Chat Core version: 
 - Flutter version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Additional context**

**Comment by Boehrsi** [comment]
Should be fixed, is currently tested.
