### ISSUE TITLE
Keyboard overlays sharing options for received/sent video/pictures/files

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#506]
**Describe the bug**
Keyboard overlays sharing options for received/sent video/pictures/files

**To Reproduce**
Occurrence: always
1. Go to Chat
2. Set focus in textfield
3. Long tab on any received or sent video/picture/file
4. Select "share" from context menu
5. Check attached screenshot 

**Expected behavior**
Keyboard should disappear if sharing menu is open. I think it's a matter of changed focus. The focus should switch from text field to sharing video/picture/file. Maybe the keyboard won't appear.

**Screenshots**
![IMG_AC82B9371D35-1](https://user-images.githubusercontent.com/62440505/78342609-d3147200-7599-11ea-9ad5-f361d698e926.jpeg)

**App information (please complete the following information):**
 - App version: 0.600.1 (514)
 - Plugin version: 
 - Delta Chat Core version: 
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max, iPhone SE
 - OS: iOS 13.4

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-???).

**Comment by phranck** [comment]
I can confirm that.

**Comment by Boehrsi** [comment]
Information for the developer: No problem on Android
