### ISSUE TITLE
API keys exposed

### ISSUE THREAD

**Issue by mrxris1337** [open-xchange/ox-coi#537]
**Describe the bug**
API keys exposed:
https://github.com/open-xchange/ox-coi/blob/master/ios/OX%20Coi/Firebase/GoogleService-Info-Development.plist

**To Reproduce**
Occurrence: [always / 5 out of 10 times / rarely]
1. Go to '...https://github.com/open-xchange/ox-coi/blob/master/ios/OX%20Coi/Firebase/GoogleService-Info-Development.plistn '....'
3. Scroll down to 'API Key'
4. See API Key

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App version: [e.g. 0.4.0]
 - Plugin version: [e.g. 0.4.0]
 - Delta Chat Core version: [e.g. 0.40.0]
 - Flutter version: [e.g. 1.0]

**Smartphone (please complete the following information):**

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-???).

**Comment by mrxris1337** [comment]
Dupe, D`Oh, found it again, didnt realize I already reported, see #443

**Comment by Boehrsi** [comment]
Thanks anyhow for having an eye on such things. 👍
