### ISSUE TITLE
Flagged message don't appear in the flagged list

### ISSUE THREAD

**Issue by Dougnkong** [open-xchange/ox-coi#568]
**Describe the bug**
After message is flagged in the chat, it is appeared as flagged, 
but the same message is not appeared in the flagged list. 

**To Reproduce**
The problem always appear when message is flagged.

1. From the chat list
2. Go to one chat you need
3. Write a message and sends it
4. Press long the sent message 
5. Tap Flag/Unflag
6. Go to profile 
7. Tap Flagged messages icon 
8. The list is blank

**Expected behavior**
The flagged message is suppose to appear in the flagged list

**App information (please complete the following information):**
 - App version: Beta-7
 - Plugin version: latest
 - Delta Chat Core version: latest
 - Flutter version:  v1.17.0

**Smartphone (please complete the following information):**
 - Device: android emulator-5554

**Comment by Boehrsi** [comment]
Due to the last clean up the MessageListBloc is missing. One should be made accessible and the FlaggedBloc should get deleted.
