### ISSUE TITLE
Move invite view to the chat list

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#58]
**Is your feature request related to a problem? Please describe.**
The user should be able to see invites in the chat list. The extra invite view should get removed.

**Describe the solution you'd like**
The already given logic should be used and the multi-view-invite (separate chat list and invite list) handling should get changed to a single-view-invite (combined chat list and invite list) handling. The given designs should get used. We have to assure that no unwanted list reloading is performed. Only one list entry should be shown for a contact, even if multiple messages were received.

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-163)

**Comment by robert-virkus** [comment]
Note that invites should not be shown within the chat list, when the anti-mobbing setting is active, compare https://github.com/open-xchange/ox-coi/issues/129.

**Comment by florianhaar** [comment]
Done and merged
