### ISSUE TITLE
Empty chat appeared

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#580]
**Describe the bug**
An empty chat appeared after importing an autocypt setup message originating from another OX COI Messenger instance.

**To Reproduce**
Occurrence: [always]
1. Have OX COI Messenger installed twice, e.g. on different devices or a developer version along with a stable version.
2. Sign in with the same account on both installations.
3. Transfer the autocrypt setup from one to another instllation
4. For me an empty chat appeared after successfully importing the autocrypt setup message.
5. Tab on the empty chat, a never-ending spinner is shown. When you now interrupt the OX, e.g. by locking the screen shortly, a DCC message is shown.

**Expected behavior**
No empty chat should appear.

**Screenshots**
![20200522_105922000_iOS](https://user-images.githubusercontent.com/837669/82673918-d4c9f000-9c42-11ea-9ce5-ab4544d38769.png)
![20200522_133429000_iOS](https://user-images.githubusercontent.com/837669/82673920-d5628680-9c42-11ea-9135-8bb49dd938a6.png)

**App information (please complete the following information):**
 - App version: 0.700.1 (517)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-???).

**Comment by Boehrsi** [comment]
DCC added a new flow for "device messages". I assume this chat appears due to this new feature, which is currently not handled by the app in a correct way (not at all).
