### ISSUE TITLE
Add search for the chat list

### ISSUE THREAD

**Issue by Boehrsi** [open-xchange/ox-coi#64]
**Is your feature request related to a problem? Please describe.**
The user should be able to search for messages from the chat view.

**Describe the solution you'd like**
- Add a search icon on the chat list screen
- Tapping on the icon opens the search
- Performing a search should use given DCC functions
  - https://c.delta.chat/classdc__context__t.html#a777bb1e11d7ea0288984ad23c2d8663b
  - https://c.delta.chat/classdc__context__t.html#a709a7b5b9b606d85f21e988e89d99fef
- A list of results should be shown, separated by type
  - TYPE_MESSAGE: All messages containing the search parameter
    - Tapping opens the chat the message belongs to. It should get scrolled to the tapped message
  - TYPE_CHAT / TYPE_CONTACT: All chats containing a user matching the search parameter
    - Tapping opens the chat

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-103)

**Comment by florianhaar** [comment]
done and merged
